# Generated by Django 3.2.16 on 2022-11-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.TextField()),
                ('q_id', models.IntegerField()),
                ('statement', models.TextField()),
                ('groundtruths', models.TextField()),
                ('solution', models.TextField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.TextField()),
                ('is_open', models.BooleanField()),
            ],
        ),
    ]
