# Generated by Django 4.1.3 on 2022-11-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("b_id", models.TextField()),
                ("u_ids", models.TextField()),
                ("is_open", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t_id", models.TextField()),
                ("q_id", models.IntegerField()),
                ("statement", models.TextField()),
                ("groundtruths", models.TextField()),
                ("solution", models.TextField()),
                ("score", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t_id", models.TextField()),
                ("q_id", models.IntegerField()),
                ("obtained_marks", models.FloatField()),
                ("total_marks", models.FloatField()),
                ("email", models.CharField(max_length=122)),
                ("solution", models.TextField()),
                ("t_cases", models.IntegerField()),
                ("p_cases", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t_id", models.TextField()),
                ("is_open", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("u_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("email", models.TextField()),
                ("phone", models.TextField()),
                ("degree", models.TextField()),
                ("year", models.TextField()),
                ("dob", models.DateField()),
                ("allowed_test", models.TextField()),
                ("username", models.TextField()),
                ("password", models.TextField()),
                ("is_active", models.BooleanField()),
            ],
        ),
    ]
