# Generated by Django 3.2.16 on 2022-11-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_test', '0002_batches_results_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
