# Generated by Django 3.2.16 on 2022-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_test', '0003_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
